#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get update 
sudo apt-get -y install haproxy

# Configure haproxy
cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
listen load_balancer
        bind :80
	mode http
	option httpclose
	option forwardfor
        balance roundrobin
        server 298885-web-01 52.86.95.57:80 check
        server 298885-web-02 35.174.200.246:80 check
EOF

# Restart haproxy using init script
sudo /etc/init.d/haproxy restart
